include: package:very_good_analysis/analysis_options.3.0.1.yaml
linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
    prefer_relative_imports: true
    invariant_booleans: false
    sort_pub_dependencies: false
    invalid_annotation_target: false
analyzer:
  plugins:
    - dart_code_metrics
  errors:
    missing_required_param: error
    missing_return: warning
    todo: ignore
    invalid_annotation_target: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 25
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 75
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - prefer-conditional-expressions
    - no-equal-then-else
    - missing_return
