name: markdown_note_mobile
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^5.0.1
  connectivity_plus: ^2.3.6+1
  dio: ^4.0.6
  expandable: ^5.0.1
  flutter_dotenv: ^5.0.2
  flutter_markdown: ^0.6.12
  flutter_riverpod: ^2.0.0-dev.9
  flutter_secure_storage: 6.0.0
  flutter_keyboard_visibility: ^5.3.0
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.1
  intl: ^0.17.0
  json_annotation: ^4.6.0
  lottie: ^1.4.1
  meta: ^1.7.0
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4
  keyboard_actions: ^4.1.0
  flutter_colorpicker: ^1.0.3
  timeago: ^3.3.0
  markdown_widget: ^1.3.0+2

dev_dependencies:
  #flutter_test:
  #sdk: flutter
  auto_route_generator: ^5.0.2
  build_runner:
  dart_code_metrics: ^4.19.1
  dependency_validator: ^3.2.2
  flutter_gen_runner:
  freezed: ^2.1.0+1
  import_sorter: ^4.6.0
  json_serializable:
  logger:
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  very_good_performance: ^0.0.4

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)

  integrations:
    flutter_svg: true
    flare_flutter: true

  assets:
    enabled: true
  fonts:
    enabled: true
import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/.env.production
    - assets/env/.env.staging
    - assets/env/.env.development
    - assets/env/
    - assets/icons/
    - assets/images/
    - assets/html/
    - assets/
